import sys
import os

# Standard template for script.py.mako
"""
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab2aea88af2'
down_revision = 'e416ad290417'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('votacao_id', sa.String(length=50), nullable=False),
    sa.Column('politico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_voto', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['politico_id'], ['politicos.id'], ),
    sa.ForeignKeyConstraint(['votacao_id'], ['votacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    # ### end Alembic commands ###
