import sys
import os

# Standard template for script.py.mako
"""
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c06cafdd92f'
down_revision = 'd6903bf1a70b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicos', sa.Column('id_legislatura', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicos', 'id_legislatura')
    # ### end Alembic commands ###
