import sys
import os

# Standard template for script.py.mako
"""
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6903bf1a70b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entidade_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('score_anomalia', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('resumo_critico', sa.Text(), nullable=True),
    sa.Column('impacto_financeiro', sa.String(length=50), nullable=True),
    sa.Column('grupos_beneficiados', sa.JSON(), nullable=True),
    sa.Column('riscos_corrupcao', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cnpj')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('sys_ingestion_dlq',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('origin_source', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_civil', sa.String(length=255), nullable=False),
    sa.Column('nome_parlamentar', sa.String(length=255), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_gabinete',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.Integer(), nullable=False),
    sa.Column('politico_id', sa.Integer(), nullable=False),
    sa.Column('empresa_cnpj', sa.String(length=20), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('tipo_despesa', sa.String(length=255), nullable=True),
    sa.Column('url_documento', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_cnpj'], ['empresas.cnpj'], ),
    sa.ForeignKeyConstraint(['politico_id'], ['politicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos_gabinete')
    op.drop_table('politicos')
    op.drop_table('sys_ingestion_dlq')
    op.drop_table('partidos')
    op.drop_table('empresas')
    op.drop_table('analises_ia')
    # ### end Alembic commands ###
