import sys
import os

# Standard template for script.py.mako
"""
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e416ad290417'
down_revision = 'e887ea656990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votacoes', sa.Column('proposicao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votacoes', 'proposicoes', ['proposicao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votacoes', type_='foreignkey')
    op.drop_column('votacoes', 'proposicao_id')
    # ### end Alembic commands ###
