import sys
import os

# Standard template for script.py.mako
"""
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ac90b0e084'
down_revision = '2ab2aea88af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoria_proposicao',
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('politico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['politico_id'], ['politicos.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('proposicao_id', 'politico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autoria_proposicao')
    # ### end Alembic commands ###
